#Written by rmanojcse06@gmail.com
FROM openjdk:8-alpine
COPY . /usr/src/rest-app
WORKDIR /usr/src/rest-app
EXPOSE 19990 
COPY /target/login-service-0.0.1-SNAPSHOT.jar login-service.jar 
ENTRYPOINT ["java","-jar","login-service.jar"]